drop table if exists bookmarks;

create table bookmarks(
    id INTEGER primary key generated by default as identity,
    created TIMESTAMPZ,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    desc TEXT DEFAULT 'Describe website here.',
    rating INTEGER,
)

insert into bookmarks(title, url, desc, rating)
values
    ('facebook','http://www.facebook.com/','a popular social media site',4),
    ('youtube','http://youtube.com/','a popular video sharing site',5),
    ('google','https://www.google.com/','a popular search engine',5),
    ('ask jeeves','https://www.ask.com/','a terribly outdated search engine',1),
    ('netflix','https://www.netflix.com/','a popular streaming video site',3),
    ('amazon','https://www.amazon.com/','a popular e-commerce site',3),
    ('reverb','https://www.reverb.com/','a popular place to buy and sell used music equipment',5),
    ('ebay','https://www.ebay.com/','a popular community e-commerce site',4),
    ('udemy','https://www.udemy.com/','a popular education resource',5),
    ('stackoverflow','https://stackoverflow.com/','a forum for coders',5);